In [53]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,LSTM,Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [54]:
sentences = [
    "Python is popular for machine learning due to simplicity.",
    "Scikit-learn is a powerful library for classical algorithms.",
    "TensorFlow is used for building neural networks.",
    "PyTorch offers dynamic computation graphs for models.",
    "Pandas is essential for data manipulation in projects.",
    "Numpy supports large arrays and matrices.",
    "Matplotlib is used for data visualization.",
    "Seaborn provides a high-level interface for plotting.",
    "Keras is an API for building neural networks.",
    "Jupyter Notebooks are ideal for interactive experiments.",
    "Feature engineering improves model performance.",
    "Data cleaning is the first step in any pipeline.",
    "Hyperparameter tuning boosts model accuracy.",
    "Cross-validation evaluates model robustness.",
    "Overfitting occurs when a model learns noise.",
    "Underfitting happens when a model is too simple.",
    "Regularization helps combat overfitting.",
    "Train-test split is fundamental for evaluation.",
    "Random Forest is an ensemble method with trees.",
    "Support Vector Machines work for high-dimensional spaces.",
    "K-Nearest Neighbors is a simple learning algorithm.",
    "Gradient Boosting combines weak learners effectively.",
    "Logistic Regression is for binary classification.",
    "Linear Regression is basic regression analysis.",
    "Naive Bayes is a probabilistic classifier.",
    "Principal Component Analysis reduces dimensionality.",
    "Clustering algorithms group similar data points.",
    "K-Means is a popular clustering algorithm.",
    "Hierarchical Clustering builds a tree of clusters.",
    "Reinforcement Learning trains agents to make decisions.",
    "Deep Learning models mimic the human brain.",
    "Convolutional Neural Networks excel in image tasks.",
    "Recurrent Neural Networks handle sequential data.",
    "LSTMs manage long-term dependencies in sequences.",
    "Transfer learning uses pre-trained model weights.",
    "Autoencoders are for unsupervised learning tasks.",
    "GANs generate data similar to training set.",
    "Ensemble methods improve model predictions.",
    "Bagging reduces variance and prevents overfitting.",
    "Boosting reduces bias in models.",
    "AdaBoost is a popular boosting technique.",
    "XGBoost is known for speed and performance.",
    "LightGBM is efficient for distributed training.",
    "CatBoost handles categorical features automatically.",
    "Feature selection reduces model complexity.",
    "One-hot encoding converts categorical variables.",
    "Label encoding assigns integers to categories.",
    "Data augmentation increases training diversity.",
    "Batch normalization speeds up training.",
    "Dropout prevents overfitting in models.",
    "Learning rate schedules adjust rates during training.",
    "Early stopping halts when validation decreases.",
    "Model checkpoints save the best model.",
    "TensorBoard visualizes TensorFlow models.",
    "PyTorch Lightning is a wrapper for PyTorch.",
    "Scipy is used for scientific computing.",
    "OpenCV is for computer vision applications.",
    "NLP tasks use SpaCy and NLTK libraries.",
    "BERT is state-of-the-art for NLP.",
    "Tokenization splits text into tokens.",
    "Word embeddings represent words as vectors.",
    "Sentiment analysis determines text sentiment.",
    "Time series forecasting predicts future data.",
    "ARIMA is popular for time series analysis.",
    "Prophet is a tool for forecasting.",
    "Anomaly detection identifies rare events.",
    "Data imputation fills missing values.",
    "SMOTE handles imbalanced datasets.",
    "ROC curve evaluates classification models.",
    "Precision and recall assess classification accuracy.",
    "F1 score is the harmonic mean of precision and recall.",
    "Confusion matrix summarizes prediction results.",
    "Grid search optimizes hyperparameters.",
    "Random search explores hyperparameter space.",
    "Bayesian optimization tunes hyperparameters efficiently.",
    "Feature scaling normalizes features.",
    "Pipelines automate machine learning workflows.",
    "Dask enables parallel computing in Python.",
    "Apache Spark is for distributed computing.",
    "ELU activation helps in learning patterns.",
    "Leaky ReLU addresses 'dying ReLU' problem.",
    "Sigmoid activation is for binary tasks.",
    "Softmax is for multi-class classification.",
    "Adam optimizer is used for training models.",
    "RMSprop adapts learning rates.",
    "SGD with momentum accelerates gradients.",
    "Backpropagation updates neural network weights.",
    "Weight initialization affects convergence.",
    "Data pipelines manage data flow.",
    "Azure Machine Learning provides cloud services.",
    "Google Cloud AI offers AI tools.",
    "Amazon SageMaker simplifies model deployment.",
    "IBM Watson provides AI application tools.",
    "sklearn.metrics provides evaluation metrics.",
    "sklearn.model_selection has data splitting tools.",
    "imbalanced-learn handles class imbalance.",
    "sklearn.decomposition offers dimensionality reduction.",
    "sklearn.ensemble provides ensemble methods.",
    "sklearn.feature_selection helps select features.",
    "sklearn.preprocessing is used for preprocessing."
]

In [55]:
print(len(sentences))

100


In [56]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(sentences)
total_word=len(tokenizer.word_index)+1
print(total_word)
print(tokenizer.word_index)

input_sequence=[]

for line in sentences:
  token_list=tokenizer.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    n_gram_sequences=token_list[:i+1]
    input_sequence.append(n_gram_sequences)


max_sequence_len=max([len(x) for x in input_sequence])
input_sequence=np.array(pad_sequences(input_sequence,maxlen=max_sequence_len,padding='pre'))
print(input_sequence)

361
{'is': 1, 'for': 2, 'data': 3, 'model': 4, 'learning': 5, 'a': 6, 'in': 7, 'models': 8, 'and': 9, 'training': 10, 'sklearn': 11, 'used': 12, 'neural': 13, 'provides': 14, 'the': 15, 'popular': 16, 'to': 17, 'networks': 18, 'feature': 19, 'overfitting': 20, 'ensemble': 21, 'classification': 22, 'analysis': 23, 'reduces': 24, 'tasks': 25, 'machine': 26, 'pytorch': 27, 'offers': 28, 'when': 29, 'helps': 30, 'boosting': 31, 'regression': 32, 'clustering': 33, 'of': 34, 'handles': 35, 'features': 36, 'selection': 37, 'computing': 38, 'ai': 39, 'tools': 40, 'python': 41, 'learn': 42, 'algorithms': 43, 'tensorflow': 44, 'building': 45, 'high': 46, 'an': 47, 'are': 48, 'performance': 49, 'hyperparameter': 50, 'accuracy': 51, 'validation': 52, 'evaluates': 53, 'simple': 54, 'evaluation': 55, 'random': 56, 'with': 57, 'k': 58, 'algorithm': 59, 'binary': 60, 'dimensionality': 61, 'similar': 62, 'manage': 63, 'weights': 64, 'methods': 65, 'prevents': 66, 'distributed': 67, 'categorical': 68, '

# data preparing

In [57]:
X=input_sequence[:,:-1]
print("input Data",X)
y=input_sequence[:,-1]
# print("Labels",y)
y=tf.keras.utils.to_categorical(y,num_classes=total_word)

input Data [[ 0  0  0 ...  0  0 41]
 [ 0  0  0 ...  0 41  1]
 [ 0  0  0 ... 41  1 16]
 ...
 [ 0  0  0 ... 11 87  1]
 [ 0  0  0 ... 87  1 12]
 [ 0  0  0 ...  1 12  2]]


In [58]:
model=Sequential([
    Embedding(total_word,10,input_length=max_sequence_len-1),
    SimpleRNN(100),
    Dense(total_word,activation='softmax')

])

In [59]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [60]:
model.fit(X,y,epochs=50,verbose=1)

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 46ms/step - accuracy: 0.0226 - loss: 5.8693
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0703 - loss: 5.5309
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0630 - loss: 5.2905 
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0716 - loss: 5.2733 
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0613 - loss: 5.2528 
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0512 - loss: 5.3155 
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0664 - loss: 5.3040 
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0955 - loss: 5.2105 
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0822 - loss: 5.2170 
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0943 - loss: 5.1216 
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1017 - loss: 4.9825 
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0

In [61]:
def predict_next_word(seed_text,next_word=2):
  for _ in range(next_word):
    token_list=tokenizer.texts_to_sequences([seed_text])[0]
    token_list=pad_sequences([token_list],maxlen=max_sequence_len,padding='pre')
    predicted=model.predict(token_list,verbose=0)
    predicted_word_index=np.argmax(predicted,axis=1)[0]
    predicted_word=tokenizer.index_word[predicted_word_index]
    seed_text+=" "+predicted_word

  return seed_text


In [62]:
print(predict_next_word("Linear"))

Linear learning is


# Building Long Short Term memory(LSTM)

In [63]:
model=Sequential([
    Embedding(total_word,10,input_length=max_sequence_len-1),
    LSTM(100),
    Dense(total_word,activation='softmax')

])

In [64]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [65]:
model.fit(X,y,epochs=50,verbose=1)

Epoch 1/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0307 - loss: 5.8871
Epoch 2/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0414 - loss: 5.8379
Epoch 3/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0692 - loss: 5.4147
Epoch 4/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0541 - loss: 5.2848
Epoch 5/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0542 - loss: 5.2682
Epoch 6/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0488 - loss: 5.2454
Epoch 7/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0469 - loss: 5.2894
Epoch 8/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0615 - loss: 5.2897
Epoch 9/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0565 - loss: 5.2264
Epoch 10/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0718 - loss: 5.2192
Epoch 11/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0691 - loss: 5.2463
Epoch 12/50
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0797 - lo

In [66]:
def predict_next_word(seed_text,next_word=2):
  for _ in range(next_word):
    token_list=tokenizer.texts_to_sequences([seed_text])[0]
    token_list=pad_sequences([token_list],maxlen=max_sequence_len,padding='pre')
    predicted=model.predict(token_list,verbose=0)
    predicted_word_index=np.argmax(predicted,axis=1)[0]
    predicted_word=tokenizer.index_word[predicted_word_index]
    seed_text+=" "+predicted_word

  return seed_text


In [69]:
print(predict_next_word("Linear Regression"))

Linear Regression is a
